name: autotests

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install googletest
      run: cd test/module && sudo chmod +x install_googletest.sh && ./install_googletest.sh

    - name: Install radish
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install radish-bdd

    - name: Build naobi
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -DUSE_ASAN=1
        cd build
        ./naobi -v

    - name: Run unit tests
      working-directory: ${{github.workspace}}/build
      run: ./naobi_test

    - name: Run old style functional tests
      working-directory: ${{github.workspace}}/test/functional
      run: |
        python3 functionalTester.py

    - name: Run gherkin scenario tests
      working-directory: ${{github.workspace}}/test/gherkin
      run: radish features --write-steps-once
