name: autotests

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop
  schedule:
    - cron: '0 0,12 * * *'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install radish
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install radish-bdd

      - name: Install gcc
        run: |
          sudo apt update
          sudo apt install gcc-10 g++-10

      - name: Build asan build of naobi
        env:
          CC: gcc-10
          CXX: g++-10
        run: |
          mkdir build
          cd build
          cmake .. -DUSE_ASAN=1
          make -j
          ./naobi -v

      - name: Run unit tests
        working-directory: ${{github.workspace}}/build
        run: ./naobi_test

      - name: Run old style functional tests
        if: always()
        working-directory: ${{github.workspace}}/test/functional
        run: |
          python3 functionalTester.py

      - name: Run gherkin scenario tests
        if: always()
        working-directory: ${{github.workspace}}/test/gherkin
        run: radish features --write-steps-once --cucumber-json asan_build.json

      - name: Cucumber Report
        if: always()
        uses: deblockt/cucumber-report-annotations-action@v1.9
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/asan_build.json"



      - name: Build thread check build of naobi
        if: always()
        working-directory: ${{github.workspace}}
        env:
          CC: gcc-10
          CXX: g++-10
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake .. -DUSE_ASAN=1 -DUSE_THREAD=1
          make -j
          ./naobi -v

      - name: Run unit tests
        if: always()
        working-directory: ${{github.workspace}}/build
        run: ./naobi_test

      - name: Run old style functional tests
        if: always()
        working-directory: ${{github.workspace}}/test/functional
        run: |
          python3 functionalTester.py

      - name: Run gherkin scenario tests
        if: always()
        working-directory: ${{github.workspace}}/test/gherkin
        run: radish features --write-steps-once --cucumber-json thread_build.json

      - name: Cucumber Report
        if: always()
        uses: deblockt/cucumber-report-annotations-action@v1.9
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/thread_build.json"
