name: master

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install googletest
      run: cd test/module && sudo chmod +x test.sh && ./test.sh
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_FLAGS="-Werror"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: UnitTests
      working-directory: ${{github.workspace}}/build
      run: ./naobi_test

    - name: FunctionalTests
      working-directory: ${{github.workspace}}/test/functional
      run: python3 functionalTester.py
