  name: tagged-release
  on:
    push:
      tags:
        - "v*"
    pull_request:
      tags:
        - "v*"


  jobs:
    tagged-release:
      runs-on: ubuntu-latest
      name: Tagged Release

      steps:
        - uses: actions/checkout@v1

        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false