  name: tagged-release
  on:
    pull_request:
      branches:
        - master
    push:
      branches:
        - master

  jobs:
    tagged-release:
      runs-on: ubuntu-latest
      name: Tagged Release

      steps:
        - uses "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false